### ISSUE TITLE
Extension fails when trying to open non-existant logs in some jobs

### ISSUE THREAD

**Issue by crtschin** [FPtje/vscode-semaphore-ci#9]
The title might be misleading, because I'm not exactly sure there are no logs. In the semaphore UI, when trying to open the log of the related job, it simply fails with a message that I should `contact support`.

The extension in vscode fails though, which can probably be caught. 
I get the following error message in vscode:

```
Error running command semaphore-ci.openLogs: cannot open semaphore-ci-joblog:<semaphore project>/<job id>/<repository>%20Build.md. Detail: events is not iterable. This is likely caused by the extension that contributes semaphore-ci.openLogs.
```

**Comment by FPtje** [comment]
Thanks for reporting this issue! Hopefully commit 35d4d3a fixes it, but I can't test it right now.
